# Generated by Django 3.1.7 on 2021-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0005_user_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Id_Card',
            field=models.FileField(default='', upload_to='profiles/'),
        ),
    ]
